import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const archivoBlack = localFont({
  src: "../../public/Archivo_Black/ArchivoBlack-Regular.ttf",
  variable: "--font-archivo-black",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import StyledComponentsRegistry from "@/lib/antd";
import QueryProvider from "@/lib/query";

import { App, ConfigProvider } from "antd";
import { AuthProvider } from "@/contexts/AuthContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivoBlack.variable} antialiased`}>
        <QueryProvider>
          <StyledComponentsRegistry>
            <ConfigProvider
              theme={{
                token: {
                  fontFamily: archivoBlack.style.fontFamily,
                },
              }}
            >
              <AuthProvider>
                <App>{children}</App>
              </AuthProvider>
            </ConfigProvider>
          </StyledComponentsRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
